In [40]:
import torch

In [3]:
print(torch.__version__)

2.9.0+cu126


In [5]:
if torch.cuda.is_available():
    print("Gpu is available")
    print(f"Using GPU: {torch.cuda.get_device_name(0)}")
else:
    print("Gpu is not available")

Gpu is available
Using GPU: Tesla T4


**Create tensors**

In [6]:
#using empty
a = torch.empty(2,3)
print(a)

tensor([[6.1954e-04, 1.0900e+27, 3.6010e-12],
        [1.7419e+28, 2.8181e+20, 1.8524e+28]])


In [7]:
#check type
type(a)

torch.Tensor

In [8]:
#using Zeros
torch.zeros(2,3)

tensor([[0., 0., 0.],
        [0., 0., 0.]])

In [9]:
#using Ones
torch.ones(2,3)

tensor([[1., 1., 1.],
        [1., 1., 1.]])

In [13]:
#using rand
torch.rand(2,3)

tensor([[0.2728, 0.2281, 0.5222],
        [0.6693, 0.1869, 0.5107]])

In [34]:
#manual_seed
torch.manual_seed(10)
torch.rand(2,3)

tensor([[0.4581, 0.4829, 0.3125],
        [0.6150, 0.2139, 0.4118]])

In [35]:
#using tensor
torch.tensor([[1,2,3],[4,5,6]])

tensor([[1, 2, 3],
        [4, 5, 6]])

In [37]:
#arange
print("Using arange ->",torch.arange(0,10,2))

#using linspace
print("Using linspace ->",torch.linspace(0,10,5))

#using eye
print("Using eye ->",torch.eye(3))

#using full
print("Using full ->",torch.full((2,3),7))

Using arange -> tensor([0, 2, 4, 6, 8])
Using linspace -> tensor([ 0.0000,  2.5000,  5.0000,  7.5000, 10.0000])
Using eye -> tensor([[1., 0., 0.],
        [0., 1., 0.],
        [0., 0., 1.]])
Using full -> tensor([[7, 7, 7],
        [7, 7, 7]])


**Tensor Shapes**

In [58]:
x = torch.tensor([[1,2,3],[4,5,6]])
x.shape
# x.dtype

torch.Size([2, 3])

In [48]:
torch.empty_like(x)

tensor([[3616445622929465956, 6068937142555454773, 3617298934482483249],
        [6499319021999436846, 7309453675965983778, 8315168162784306286]])

In [49]:
torch.zeros_like(x)

tensor([[0, 0, 0],
        [0, 0, 0]])

In [50]:
torch.ones_like(x)

tensor([[1, 1, 1],
        [1, 1, 1]])

In [65]:
torch.rand_like(x,dtype=torch.float64)    # give error because chage of datatype

tensor([[0.5504, 0.9424, 0.3835],
        [0.6327, 0.5669, 0.3390]], dtype=torch.float64)

Tensor Datatypes

In [59]:
torch.tensor([1.0,2.0,3.0],dtype=torch.int32)

tensor([1, 2, 3], dtype=torch.int32)

In [60]:
torch.tensor([1,2,3],dtype=torch.float64)

tensor([1., 2., 3.], dtype=torch.float64)

In [61]:
x

tensor([[1, 2, 3],
        [4, 5, 6]])

In [63]:
#using to()
x.to(torch.float64)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)

## Scaller operation

In [67]:
#adddition
x+2

#substraction
x-2

#multiplication

x*2

#division
x/2

#power
x**2

#int division
x//2

#modulus
x%2

tensor([[1, 0, 1],
        [0, 1, 0]])

In [68]:
a = torch.rand(2,3)
b = torch.rand(2,3)
print(a)
print(b)

tensor([[0.6150, 0.4967, 0.4521],
        [0.0575, 0.0687, 0.0501]])
tensor([[0.0108, 0.0343, 0.1212],
        [0.0490, 0.0310, 0.7192]])


In [70]:
#add
a+b

#sub
a-b

#mul
a*b

#div
a/b

#power
a**b

#int div
a//b

#mod
a%b

tensor([[0.0019, 0.0162, 0.0885],
        [0.0085, 0.0068, 0.0501]])

In [71]:
c = torch.tensor([1,-2,3,-4])

#abs
torch.abs(c)

#negative
torch.neg(c)

#sign
torch.sign(c)

tensor([ 1, -1,  1, -1])

In [73]:
d = torch.tensor([1.9,2.3,3.7,4.4])

#round
torch.round(d)

#ceil
torch.ceil(d)

#floor
torch.floor(d)

#clamp
torch.clamp(d,min=2,max=3)  #range(2,3)

tensor([2.0000, 2.3000, 3.0000, 3.0000])

### Reduction Operation

In [81]:
e = torch.randint(size=(2,3),low=0,high=10,dtype=torch.float32)
e

tensor([[3., 0., 9.],
        [3., 7., 9.]])

In [79]:
#sum
torch.sum(e)
torch.sum(e,dim=0)
torch.sum(e,dim=1)

tensor([13, 17])

In [82]:
#mean
torch.mean(e)
torch.mean(e,dim=0)
torch.mean(e,dim=1)


tensor([4.0000, 6.3333])

In [83]:
#median
torch.median(e)
torch.median(e,dim=0)
torch.median(e,dim=1)


torch.return_types.median(
values=tensor([3., 7.]),
indices=tensor([0, 1]))

In [86]:
#max and min
torch.max(e)
# torch.max(e,dim=0)
# torch.max(e,dim=1)
torch.min(e)

tensor(0.)

In [87]:
#product
torch.prod(e)
torch.prod(e,dim=0)
torch.prod(e,dim=1)


tensor([  0., 189.])

In [88]:
#standard deviation
torch.std(e)

tensor(3.7103)

In [89]:
#variance
torch.var(e)

tensor(13.7667)

In [91]:
#argmax
torch.argmax(e)
torch.argmax(e,dim=0)
torch.argmax(e,dim=1)

#argmin
torch.argmin(e)
# torch.argmin(e,dim=0)
# torch.argmin(e,dim=1)


tensor(1)

# Matrix Multiplication

In [96]:
f = torch.randint(size=(3,2),low = 0 , high = 10)
g = torch.randint(size=(2,3),low = 0 , high = 10)
print(f)
print(g)

tensor([[7, 4],
        [9, 6],
        [4, 4]])
tensor([[6, 6, 5],
        [6, 3, 6]])


In [97]:
#matrix multiplication
torch.matmul(f,g)

tensor([[66, 54, 59],
        [90, 72, 81],
        [48, 36, 44]])

In [98]:
vector1 = torch.tensor([1,2])
vector2 = torch.tensor([3,4])

#dot product
torch.dot(vector1,vector2)

tensor(11)

In [99]:
#transpose
torch.transpose(f,0,1)


tensor([[7, 9, 4],
        [4, 6, 4]])

In [103]:
h = torch.randint(size=(3,3),low = 0 , high = 10 , dtype=torch.float64)
h

tensor([[7., 5., 2.],
        [0., 3., 0.],
        [8., 1., 6.]], dtype=torch.float64)

In [104]:
#determinant
torch.det(h)

tensor(78., dtype=torch.float64)

In [105]:
#inverse
torch.inverse(h)

tensor([[ 0.2308, -0.3590, -0.0769],
        [ 0.0000,  0.3333,  0.0000],
        [-0.3077,  0.4231,  0.2692]], dtype=torch.float64)

## Comparision Operation

In [106]:
i = torch.randint(size=(3,3),low = 0 , high = 10)
j = torch.randint(size=(3,3),low = 0 , high = 10)
print(i)
print(j)

tensor([[8, 8, 4],
        [2, 6, 3],
        [5, 1, 4]])
tensor([[4, 0, 3],
        [5, 9, 5],
        [6, 9, 0]])


In [111]:
#greater than
i>j

#less than
i<j

#equal to
i == j

#not equal to
i != j

#greater than equal to
i>=j

#less than equal to
i<=j

tensor([[False, False, False],
        [ True,  True,  True],
        [ True,  True, False]])

# Special Function

In [116]:
k = torch.randint(size=(3,3),low = 0 , high = 10 ,dtype = torch.float64)
k

tensor([[2., 6., 6.],
        [2., 7., 3.],
        [9., 5., 8.]], dtype=torch.float64)

In [117]:
#log
torch.log(k)

tensor([[0.6931, 1.7918, 1.7918],
        [0.6931, 1.9459, 1.0986],
        [2.1972, 1.6094, 2.0794]], dtype=torch.float64)

In [118]:
#exp
torch.exp(k)

#sqrt
torch.sqrt(k)

#sigmoid
torch.sigmoid(k)

tensor([[0.8808, 0.9975, 0.9975],
        [0.8808, 0.9991, 0.9526],
        [0.9999, 0.9933, 0.9997]], dtype=torch.float64)

In [119]:
#softmax
torch.softmax(k,dim=0)

tensor([[9.1022e-04, 2.4473e-01, 1.1850e-01],
        [9.1022e-04, 6.6524e-01, 5.8998e-03],
        [9.9818e-01, 9.0031e-02, 8.7560e-01]], dtype=torch.float64)

In [120]:
#relu
torch.relu(k)

tensor([[2., 6., 6.],
        [2., 7., 3.],
        [9., 5., 8.]], dtype=torch.float64)

# Inplace Operation

In [126]:
m = torch.rand(3,2)
n = torch.rand(3,2)
print(m)
print(n)

tensor([[0.0231, 0.6404],
        [0.5023, 0.8459],
        [0.5840, 0.1057]])
tensor([[0.9714, 0.0698],
        [0.7400, 0.1518],
        [0.7698, 0.6248]])


In [127]:
m+n

tensor([[0.9945, 0.7102],
        [1.2424, 0.9977],
        [1.3538, 0.7305]])

In [128]:
m

tensor([[0.0231, 0.6404],
        [0.5023, 0.8459],
        [0.5840, 0.1057]])

In [129]:
m.add_(n)

tensor([[0.9945, 0.7102],
        [1.2424, 0.9977],
        [1.3538, 0.7305]])

In [130]:
m

tensor([[0.9945, 0.7102],
        [1.2424, 0.9977],
        [1.3538, 0.7305]])

In [133]:
m.relu_()

tensor([[0.9945, 0.7102],
        [1.2424, 0.9977],
        [1.3538, 0.7305]])